# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(430, 420))
        MainWindow.setMaximumSize(QtCore.QSize(430, 420))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 411, 220))
        self.groupBox.setObjectName("groupBox")
        self.text = QtWidgets.QTextEdit(self.groupBox)
        self.text.setGeometry(QtCore.QRect(0, 20, 410, 200))
        self.text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.text.setObjectName("text")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 240, 411, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choice_image = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.choice_image.setObjectName("choice_image")
        self.verticalLayout_2.addWidget(self.choice_image)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choice_file = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.choice_file.setObjectName("choice_file")
        self.horizontalLayout.addWidget(self.choice_file)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.send_message = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.send_message.setObjectName("send_message")
        self.verticalLayout_2.addWidget(self.send_message)
        self.progress_sent_message = QtWidgets.QLabel(self.centralwidget)
        self.progress_sent_message.setGeometry(QtCore.QRect(20, 370, 401, 16))
        self.progress_sent_message.setObjectName("progress_sent_message")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 390, 411, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mailing list in telegram"))
        self.groupBox.setTitle(_translate("MainWindow", "Текст"))
        self.choice_image.setText(_translate("MainWindow", "Выберите картинку"))
        self.label.setText(_translate("MainWindow", "Выберите exel таблицу и столбик номеров"))
        self.choice_file.setText(_translate("MainWindow", "Выбрать файл"))
        self.send_message.setText(_translate("MainWindow", "Отправить"))
        self.progress_sent_message.setText(_translate("MainWindow", "Отправлено 0"))
